#!/usr/bin/zsh

find ./cases -type f -delete

echo "Cleaned ./cases"

for ((i = 0; i < 20; i++))
do
    if wget -q "https://judgegirl.csie.org/downloads/testdata/$1/$i.in" -P "./cases" && 
       wget -q "https://judgegirl.csie.org/downloads/testdata/$1/$i.out" -P "./cases"; then
        echo "Downloaded $i.in and $i.out"
    fi
done
