#!/usr/bin/zsh

make

for ((i = 0; i <= 10; i++))
do
    if [ -f "./cases/$i.in" ]; then
        ./65 < "./cases/$i.in" > tmp
        if cmp -s -- "tmp" "./cases/$i.out"; then
            printf "%2d: OK\n" $i
        else
            printf "%2d: NOT OK\n" $i
        fi
    fi
done

[ -f tmp ] && rm tmp
